service: tidbyt-updater
frameworkVersion: '3'

useDotenv: true

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-2

functions:
  tidbyt:
    name: "tidbytUpdater"
    description: "Update custom widgets on my Tidbyt"
    handler: handler.tidbyt
    environment:
      API_TOKEN: "${env:API_TOKEN}"
      DEVICE_ID: "${env:DEVICE_ID}"
    events:
      - schedule: rate(1 hour)
